id: AD9645504
title: Prayer for the Swift Rebirth of Jamyang Khyenrab Tayé
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:34:42.433106
  last_modified_at: 2022-02-28 23:34:42.433117
